### ISSUE TITLE
Font size variables should resolve to exact pixels.

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#164]
Currently, most of our font size variables (all set in `em`) don't equate to nicely rounded pixel sizes:

| Variable  | Pixel Size  |
|---|---|
| `$font__size-xs`  |  `15.644px` |
|  `$font__size-sm` |  `19.555px` |
| `$font__size-md`  | `22px`  |
| `$font__size-lg`  | `37.125px`  |
| `$font__size-xl`  | `49.5px`  |
| `$font__size-xxl`  | `61.875px`  |

This can lead to messy half-pixel rendering — we should revise our type scale so that it results in exact, crisp, pixel-perfect text. 💎 🎉

**Comment by joyously** [comment]
Why do they have to go to pixels at all?
If that is a requirement of GB, it needs to be fixed there, not in the theme.

**Comment by kjellr** [comment]
@joyously I’m just referring to when the text is actually rendered by the browser.

**Comment by 2ndkauboy** [comment]
You are right, we should probaby target for exact calculated pixel values. Should we use the next best rounded value or should we use steps, a use might now from other programs, like Word (16, 18, 20, 22, 24, 26, 28, 36, 48) or Pages (14, 18, 24, 36, 48, 64):


| Variable | Rounded | Word/Pages
| -- | -- | -- |
| $font__size-xs | 16px (`/ 1.546875`) | 16px | (`/ 1.546875`) 
| $font__size-sm | 20px  (`/ 1.2375`) | 20px  (`/ 1.2375`) |
| $font__size-md | 22px  (`/ 1`) | 22px  (`/ 1`) |
| $font__size-lg | 28px  (`/ 1`) | 28px  (`/ 1`) |
| $font__size-xl | 50px  (`/ 0.495`) | 48px  (`/ 0.515625`) |
| $font__size-xxl | 62px  (`/ 0.3991935483870968`) | 64px  (`/ 0.38671875`) |

Using those steps for the content font-sizes might be handy, as users are used the those proportions.

Note: I used devision instead of multiplication, as those are the only one not resulting in repeating decimal.

**Comment by 2ndkauboy** [comment]
In the PR, I used the values from the column "Word/Pages" (but used `13px` for `$font__size-xxs`).

Example: the `$font__size-xl` now rounds to `2.18182em` which is `48.00004px`, which should be exact enough for the browser (at least I cannot see any repaint when switching to the exact value of `48px` in Chrome).

**Comment by kjellr** [comment]
We're in the process of closing down this GitHub repository now that the theme is merged into core, so I've migrated this issue over to Trac:

https://core.trac.wordpress.org/ticket/45899 

I'm closing this issue a result. Please feel free to follow up in the new thread moving forward.
