### ISSUE TITLE
Old Instagram Icon

### ISSUE THREAD

**Issue by timbowen** [WordPress/twentynineteen#20]
Looking at the theme screenshot I noticed the old Instagram logo is being used: http://cs.zone/Wis7ov

This logo was updated in 2016. Remember to use the new one :)

**Comment by lancewillett** [comment]
Good eye, Tim!

**Comment by kjellr** [comment]
Very good catch @timbowen! Looks like this was fixed in the theme itself though. It [currently pulls in](https://github.com/WordPress/twentynineteen/blob/be850d11ee31434ad700db518ff8570f82e65b9c/classes/class.twentynineteen-svg-icons.php#L286) the current instagram logo:

![screen shot 2018-10-16 at 10 50 52 am](https://user-images.githubusercontent.com/1202812/47025445-7d43d400-d131-11e8-8e36-0be74f9411f8.png)

Marking as closed for now. 👍
