### ISSUE TITLE
Update PHPCS ruleset

### ISSUE THREAD

**Issue by dimadin** [WordPress/twentynineteen#220]
PHPCS ruleset that was added in d12ed85 is three years old, ported [from](https://github.com/WordPress/twentysixteen/commit/24b6bcb6ab1648edf864b06b43d415a95da5f418#diff-fb9be57a9891d5b859fae14629f8c441) Twenty Sixteen. In the meantime, WPCS got a lot of updates, and this summer got stable version.

**Comment by Nikschavan** [comment]
Here are some changes that can be considered - 

- It should be checked if the [excluded rules](https://github.com/WordPress/twentynineteen/blob/master/phpcs.xml.dist#L11-L19) really need to be excluded. Most of these seem related to indentation and phpDoc.
- Setting up WordPress and the database does not seemt to be required as no PHPunit or database interaction is used. [link](https://github.com/WordPress/twentynineteen/blob/master/.travis.yml#L44-L62)
- The main reason for running [different PHP versions in travis](https://github.com/WordPress/twentynineteen/blob/master/.travis.yml#L17-L26) seems to be for checking for PHP errors, Instead of this [PHPCompatibility/PHPCompatibilityWP](https://github.com/PHPCompatibility/PHPCompatibilityWP) can be used.
- Instead of [downloading and setting up PHPCS manually](https://github.com/WordPress/twentynineteen/blob/master/.travis.yml#L64-L72), composer packages can be used from a composer.json [like WordPress](https://github.com/WordPress/wordpress-develop/blob/master/composer.json#L12-L15).

**Comment by desrosj** [comment]
Tackled in #448

**Comment by laurelfulford** [comment]
The Core version of Twenty Nineteen doesn't include the `travis.yml` file; since we're closing out this repo to move the theme development fully to the Core Trac, I'm going to close this issue. Thanks!
