### ISSUE TITLE
IE11: Cover Image text not vertically centered

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentynineteen#269]
In IE11, when using `aligncenter`, `alignfull` or `alignwide` on a Cover Image with text, the text is not vertically centered over the image. 

**Chrome Align Center**
![centered-cover-image-chrome](https://user-images.githubusercontent.com/34601694/47439578-9f190880-d77a-11e8-8d80-095ed16c1fe4.PNG)

**IE11 Align Center**
![centered-cover-image-ie11](https://user-images.githubusercontent.com/34601694/47439617-ae985180-d77a-11e8-92fa-a89cbf732fe8.PNG)

**Chrome Align Wide**
![alignwide-cover-image-chrome](https://user-images.githubusercontent.com/34601694/47439702-d8ea0f00-d77a-11e8-901f-c8c0e80a6c75.PNG)

**IE11 Align Wide**
![alignwide-cover-image-ie11](https://user-images.githubusercontent.com/34601694/47439744-ea331b80-d77a-11e8-9367-1bd5a07c1db0.PNG)

**Chrome Align Full**
![alignfull-cover-image-chrome](https://user-images.githubusercontent.com/34601694/47439795-fe771880-d77a-11e8-81ee-e72b4fa88b72.PNG)

**IE11 Align Full**
![alignfull-cover-image-ie11](https://user-images.githubusercontent.com/34601694/47439899-2d8d8a00-d77b-11e8-832f-b8d804fd4791.PNG)

**Comment by kjellr** [comment]
Thanks for reporting. This issue is actually independent of the theme. Here it is without Twenty Nineteen active:

![screen shot 2018-10-24 at 11 09 18 am](https://user-images.githubusercontent.com/1202812/47441028-59117400-d77d-11e8-95d2-427eec3a3325.png)

Here's the issue for tracking in Gutenberg:

https://github.com/WordPress/gutenberg/issues/5791

I'm going to close this one, but also leave a note in the Gutenberg repo issue to hopefully move that along. 👍
