### ISSUE TITLE
Consider syncing up font smoothing between the front end and Gutenberg

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#281]
Currently, the front end of the site implements font smoothing via the following rules:

```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

These rules do not exist in the Gutenberg editor. This leads to a much heavier display of text in the editor than in the front end: 

_Front End_
![screen shot 2018-10-24 at 2 23 02 pm](https://user-images.githubusercontent.com/1202812/47452606-ab13c300-d798-11e8-8ff0-01b6eae273e7.png)

_Gutenberg_
![screen shot 2018-10-24 at 2 23 42 pm](https://user-images.githubusercontent.com/1202812/47452614-aea74a00-d798-11e8-8076-d4d133bbccdc.png)

We should consider syncing these up in one way or another.

**Comment by jasmussen** [comment]
I have opinions ;) 

And distilled to its purest essence: the editor style should look as much as possible like the theme, so if you can scope this rule to just the editing canvas, DO IT! I imagine this might work:

```
.edit-post-visual-editor * {
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
}
```

I _don't_ think that this rule should be applied to Gutenberg as a whole, or even WordPress. And in fact, outside of the benefits this had in the past to ensure icon fonts didn't get fuzzy blue/red edges, my deeply personal (emotional) opinion is that these font rendering rules should generally be avoided. Reason being: subpixel antialiasing on operating systems for fonts is an artform that's highly complicated, but ensures crispness and readibility of vectors even at small sizes. A WordPress theme sort of fits a small tiny window of exceptions to this, because I accept the argument that it's creative freedom and the theme might be using fonts that are perhaps not optimized for MacOS font rendering subpixel antialiasing.

**Comment by kjellr** [comment]
Thanks, @jasmussen. I'm not  100%  sure that something as simple as your example will work (I worry that it'll bleed into block-level controls/placeholder labels/menu text/etc.). But we can try things out and see. 👍

**Comment by laurelfulford** [comment]
Closing this issue, since it's been moved over to Trac here: https://core.trac.wordpress.org/ticket/45909
