### ISSUE TITLE
Navigation sub-menu width broken after #263

### ISSUE THREAD

**Issue by afercia** [WordPress/twentynineteen#282]
Seems to me the CSS property `max-content` introduced in https://github.com/WordPress/twentynineteen/pull/263 broke the layout of the sub-menus, see screenshot below (from Chrome on macOS):

![screen shot 2018-10-24 at 20 40 46](https://user-images.githubusercontent.com/1682452/47453657-99004780-d7cd-11e8-97aa-6996abf8d157.png)

I see the same on all browsers, on Windows too. Also, to my knowledge, `max-content` is not supported at all by Edge and IE11.

**Comment by afercia** [comment]
Forgot to mention that any style applied on `:hover` should be applied also on `:focus` otherwise there's the risk the width of the sub-menu will break when using a keyboard to navigate.

**Comment by kjellr** [comment]
Good catch. We'll need to fix. I'm not positive we need `max-content` there, but if we continue using it we'll need a fallback too.

**Comment by nielslange** [comment]
@afercia Thanks for reporting this issue. On my screen, the implementation of #263 looked as followed:

![screenshot 2018-10-25 at 07 50 37](https://user-images.githubusercontent.com/3323310/47469379-cdeeb780-d82a-11e8-972d-9e63c632a75f.png)

Top left: Chrome 69.0
Bottom left: Opera 55.0
Top right: Safari 12.0
Bottom right: Firefox 64.0b3

Since I positioned the drop-down container under the parent menu item, I used the value `max-content` to ensure that the drop-down container uses its own width instead of the width of its parent element. I wonder if the following change would fix it:

```
width: 200px
max-width: max-content;
```

I do not have access to a Windows system and therefore cannot test this issue on Edge.

**Comment by kjellr** [comment]
> I wonder if the following change would fix it:

It might — I'd have to take a look tomorrow. But I seem to remember that `max-content` in that context may also not have wide browser support. We'll have to double check on that. 

Also cc @c4rl0sbr4v0, who mentioned he'd take a look at fixing this.

**Comment by afercia** [comment]
@nielslange thanks for clarification. It's perfectly possible I've made some mistake building the CSS. However, can you please try focusing a top level item with the keyboard? In that case, `max-content` doesn't get applied. Still not supported by Edge and IE.

**Comment by kjellr** [comment]
This should be working as of #308. 👍
