### ISSUE TITLE
Fluid font sizing 

### ISSUE THREAD

**Issue by drjecker** [WordPress/twentynineteen#305]
The font size is the same for mobile as for desktop. Large font sizes on small screens can impact readability. I suggest implementing fluid type that changes based the width of the viewport.

You can see an example of this technique in this [article on CSS Tricks](https://css-tricks.com/snippets/css/fluid-typography/):

![Animated gif showing fluid type from CSS Tricks](https://css-tricks.com/wp-content/uploads/2017/02/css-fluid-text-calc.gif)

I would suggest using `1em` as the `<body>` size for mobile (typically 16px) and resize up to the theme's current of `1.375em` at a viewport width of `80em`.

Example CSS:
```
body{
  font-size:1em;
}

@media screen and (min-width: 20em) {
  body {
    font-size: calc(1em + 0.375 * ((100vw - 20em) / 60));  }
}

@media screen and (min-width: 80em) {
  body {
    font-size: 1.375em;
  }
}
```
I will note that this would not work with @kjellr's goal outlined in #164. 

Also, with a change in the base/body font-size there would need to be testing and likely adjustments to elements that rely on this value for computing things like margins, padding, line-height, etc. - e.g. it's not quite as simple as adding a few lines of CSS :)
 
Bring it up for discussion. 

For reference below are screenshots of the current theme's font-size at a typical mobile screen size next my suggested font-size:

![twenty-seventeen-suggested-fluid-font-sizing](https://user-images.githubusercontent.com/1401704/47473936-cefbf680-d7e2-11e8-9dc1-1d2383855df2.jpg)

**Comment by kjellr** [comment]
Hey @drjecker — thanks for filing the issue. The default 16px font size on mobile may be readable for some, but for many others in of the population, it's too small to comfortably read. Our large font size on all screen sizes is intentional, and is driven by an effort to be a little more inclusive. By setting an easier-to-read default body text size, we're aiming to have a positive impact on those with age-related farsightedness, and improve readability for all while we're at it. 

The exact sizes are up for debate though. As you mentioned, I do hope we revisit our font scale in general. #164 shouldn't be incompatible with a goal of nice, round, pixel sizes, if we get our math right.

**Comment by joyously** [comment]
I'm still advocating for using `html { font-size: 100%}` so that all users get what they chose in their browser, whether that is 36px or 15px. I'm one of those who feels claustrophobic when the font size is too large (I've answered forum questions about font sizes too big), and I've met many who need quite large font sizes to be able to read the text at all.

**Comment by kjellr** [comment]
Hi there! Thanks again for the feedback on this issue. We're in the process of closing down this GitHub repository now that the theme is merged into core, and as per [my notes above](
https://github.com/WordPress/twentynineteen/issues/305#issuecomment-433038950), I'm going to close this issue for now. If there's still interest, we can use this new Trac thread to discuss adding a fluid font scale to the theme:

https://core.trac.wordpress.org/ticket/45899 

Thanks again, and feel free to follow in that new thread.
