### ISSUE TITLE
post titles are bold, not showing bold markup differently

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#326]
Post titles are showing as bold, so markup for bold is not different.

![title-markup](https://user-images.githubusercontent.com/7957680/47519696-bd9f0280-d853-11e8-9216-dbed92b85a8f.jpg)

**Comment by kjellr** [comment]
@joyously What browser and operating system are you seeing this on?

_(Here's Mac OS 10.14, Safari 12.0)_
<img width="698" alt="screen shot 2018-10-25 at 1 49 06 pm" src="https://user-images.githubusercontent.com/1202812/47519974-de1f8a80-d85c-11e8-9850-7eb9ae754288.png">

**Comment by joyously** [comment]
Mine was on Ubuntu, using SeaMonkey 2.49, but it looks the same in Firefox 62.

**Comment by c4rl0sbr4v0** [comment]
I have it in Firefox working 
<img width="763" alt="screenshot 2018-10-26 at 00 08 56" src="https://user-images.githubusercontent.com/37012961/47533260-629cf800-d8b3-11e8-8c22-1a0cc0f6290d.png">

**Comment by kjellr** [comment]
My guess about this is that the Ubuntu system font we're using there may not have both bold and heavy weights included to use in this case. A quick glance at Ubuntu's design docs seems to confirm that: https://design.ubuntu.com/font/

The system fonts we call for Mac, iOS, Windows, and Android all do have Heavy/Black/ExtraBold/etc fonts to use in cases like these.

**Comment by joyously** [comment]
No, when I change this rule
```
.main-navigation, .page-description, h2.author-title, .author-description .author-link, .not-found .page-title, .error-404 .page-title, .post-navigation .post-title, .pagination .nav-links, .comments-title, .comment-author .fn, .no-comments, .site-title, h1, h2, h3, h4, h5, h6 {
  font-family: -apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen","Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue",sans-serif;
  font-weight: 700;
  letter-spacing: -0.02em;
  line-height: 1.2;
}
```
to be `font-weight: normal`, then it looks correct. This rule makes the whole thing bold.

**Comment by kjellr** [comment]
To expand a bit more on the issue here. We're currently using `bolder` to make bold text appear more bold.

This works using our font stack on Mac (San Francisco font, via `--apple-system`):

<img width="373" alt="screen shot 2018-11-26 at 1 45 47 pm" src="https://user-images.githubusercontent.com/1202812/49035704-905fb000-f183-11e8-824e-62fa7c17e956.png">

... and on Windows (Segoe UI):

<img width="396" alt="screen shot 2018-11-26 at 1 52 25 pm" src="https://user-images.githubusercontent.com/1202812/49035708-95246400-f183-11e8-8036-c6dca7025afd.png">

... and on iOS (San Francisco font, via `--apple-system`):

<img width="293" alt="screen shot 2018-11-26 at 1 51 10 pm" src="https://user-images.githubusercontent.com/1202812/49035712-981f5480-f183-11e8-959f-3b537cf79497.png">

... and on Android (Droid Sans):

<img width="363" alt="screen shot 2018-11-26 at 1 59 38 pm" src="https://user-images.githubusercontent.com/1202812/49035719-9b1a4500-f183-11e8-8140-1db09642fe56.png">

The reason this works in all those instances is because those font families support font weights that are heavier than Bold (700 weight). As per CSS Tricks: 

> The keyword values bolder and lighter are relative to the computed font weight of the parent element. The browser will look for the closest "bolder" or "lighter" weight, depending on what is available in the font family, otherwise it will simply choose "400" or "700", depending on which makes the most sense.

[As noted above](
https://design.ubuntu.com/font/), Ubuntu's system font does not include a weight bolder than 700, the browser just uses Bold there instead. 

The fix for this would be to either:  

1. Switch all post titles to a lighter font, everywhere (to me personally, this seems like overkill)
2. Switch all post titles to a lighter font, only on systems that don't bundle system font weights bolder than bold.
3. Modify the font stack so that Ubuntu uses a font with more weights. (I'm not familiar with the bundled fonts in Ubuntu, so I'm not sure this is an option). 
4. Or, we could close this as an edge case: We've noticed this only when a browser is running on Linux, viewing a post that has a bold tag in its title.

**Comment by allancole** [comment]
Based on Kjell’s comments above, I think its safe to close this as a very specific edge case. If it comes up later we can always open a new ticket on Trac and revisit a better solution :-)
