### ISSUE TITLE
Comply with WordPress CSS Coding Standards

### ISSUE THREAD

**Issue by Ismail-elkorchi** [WordPress/twentynineteen#356]
Twentynineteen don't adhere to [WordPress CSS Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/), when it should. Also, it's worth adding Stylelint to travis along with [stylelint-config-wordpress](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress) to prevent any inconsistencies in the codebase.

**Comment by anevins12** [comment]
Looking into it, assign to me

**Comment by kjellr** [comment]
Some of this was addressed in #372. The `stylelint` idea was built in #371, but closed since we're no longer using GitHub/Travis in the dev process now that the theme has been merged into core. I'm going to close this issue for now as a result, but we can open a new issue on Trac for any other specific improvements. 

Thanks!
