### ISSUE TITLE
Cover Block: Links in Text invisible on front end

### ISSUE THREAD

**Issue by bph** [WordPress/twentynineteen#369]
When I added links to the cover block text, the editor shows the text as underlined. On the front end, that doesn't show, which makes links invisible to visitors. 
Screenshot from the editor: 
<img width="698" alt="screen shot 2018-10-27 at 1 22 53 pm" src="https://user-images.githubusercontent.com/39980/47607272-da6e3e00-d9eb-11e8-945c-65d340baf6b2.png">

Screenshot from the frontend. 
<img width="932" alt="screen shot 2018-10-27 at 1 27 18 pm" src="https://user-images.githubusercontent.com/39980/47607303-11dcea80-d9ec-11e8-9b45-ef9a61ff1fcb.png">

Using WP 5.0 beta 1-43832
Google Chrome 69.0.3497.100
MacOS: 10.13.6

**Comment by kjellr** [comment]
@bph I think this may be fixed in the latest version of the theme here on Github. We lost some of our custom cover image styles when the block was renamed from "Cover Image" to "Cover" in the last version of Gutenberg, and the fix didn't make it into the Beta 1 merge. Here's how this should look now:

Back end:

<img width="602" alt="screen shot 2018-10-27 at 1 57 12 pm" src="https://user-images.githubusercontent.com/1202812/47607624-4ce11d00-d9f0-11e8-9189-e0c05012258f.png">

Front  end:

<img width="625" alt="screen shot 2018-10-27 at 1 57 22 pm" src="https://user-images.githubusercontent.com/1202812/47607636-52d6fe00-d9f0-11e8-90e4-89f7551ce8eb.png">

**Comment by joyously** [comment]
Did you reload the stylesheet? (clear cache or hit Reload) There is no version number changing for styles to reload, in this development limbo.

**Comment by kjellr** [comment]
I agree there may be some caching issues — here's how that first block looks when I view it:

<img width="1245" alt="screen shot 2018-10-27 at 10 13 29 pm" src="https://user-images.githubusercontent.com/1202812/47611139-96079000-da35-11e8-9ef8-eae2675aa841.png">

That second one is odd though — I see the unstyled text too. The markup looks unusual though... Cover block text is usually housed in a single `wp-block-cover-text` paragraph tag, but in this case that's empty and the text is in its own `p` tag. I'm not sure how that would've happened. 🤔 

<img width="833" alt="screen shot 2018-10-27 at 10 12 11 pm" src="https://user-images.githubusercontent.com/1202812/47611141-a0c22500-da35-11e8-9977-d2840afe904a.png">

**Comment by bph** [comment]
I close this as the link issue is fixed. I will test the side issue (second cover block doesn't display well on front end) and file a separate issue if it occurs again.
