### ISSUE TITLE
Gallery block is not very good compared to gallery shortcode

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#530]
Is it Gutenberg or the theme that makes the gallery block so unlike the gallery shortcode?
The shortcode shows a thumbnail linked to the larger image (attachment page by default, but could be file), with the description below.
![screenshot_2018-11-09_09-22-16](https://user-images.githubusercontent.com/7957680/48271090-27e1a680-e401-11e8-9f93-496fe00d10b0.jpg)

The block shows a small image (no link) with the description on top of it. This is a much worse user experience, because you can't see the image (it's small and has text on top) and there is no link to the larger one. Also, very small images are used the more columns there are and then the images have scroll bars.
![block gallery local current wp-1701](https://user-images.githubusercontent.com/7957680/48270727-59a63d80-e400-11e8-9dbc-5fd7a65146df.jpg)

Using WP 4.9.8, GB 4.2, Firefox 63 on Ubuntu.

**Comment by kjellr** [comment]
@joyously these are all core Gutenberg gallery styles. Twenty Nineteen only adjusts the theme's caption font. 

Here are a couple Gutenberg issuesPRs that touch on your notes: 

https://github.com/WordPress/gutenberg/issues/8030
https://github.com/WordPress/gutenberg/pull/11239

In the meantime, I'm going to close this one, since any fixes should be integrated at the Gutenberg level.
