### ISSUE TITLE
Hiding footer credit on Business plan

### ISSUE THREAD

**Issue by arcangelini** [WordPress/twentynineteen#539]
When using the `Hide` option for Footer Credit on Business plans the site-title remains along with a `,` at the end. On the other themes I have tested this removes the site-title. I don't think it needs to be completely removed, but it may be a good idea to at least remove the `,` to make it look cleaner.

![screen shot 2018-11-09 at 23 50 34](https://user-images.githubusercontent.com/33258733/48298069-4b960280-e47c-11e8-94b5-0c6327ea55e5.png)

![screen shot 2018-11-09 at 23 51 30](https://user-images.githubusercontent.com/33258733/48298070-4f298980-e47c-11e8-8a1d-4c0018478b44.png)

**Comment by kjellr** [comment]
Thanks for the report, @arcangelini! Since this is specifically related to WordPress.com functionality, the WordPress.com Theme Team will take care of a fix on their end. I've spoken with @laurelfulford about the issue, and she's logged a bug report internally for it. I'll go ahead and close this one for now. 👍
