### ISSUE TITLE
Featured Image set on Posts Page doesn't display.

### ISSUE THREAD

**Issue by igielskv** [WordPress/twentynineteen#541]
When using static Home Page and have assigned some page as a Posts Page (where all the posts are displayed). When editing that Posts Page, there is an option to set the Featured Image, but when I display the Posts Page, there is no featured image displayed even though I see that image set properly in Posts Page editor.

All the other pages, like Home Page, the Posts them self, they do display featured images properly.

I'm using using a development version (5.0-beta3-43883) with Twenty Nineteen theme.

Have good day everyone, bye.

**Comment by joyously** [comment]
That is typical usage.
The setting for Posts Page tells WordPress to query the latest posts and to use the template hierarchy starting from `home.php` which falls back to `index.php`. By the time the theme is displaying the page, everything is set to show a list of posts (although you _can_ get the page title to display).
If you reset your Posts Page to a different page, the featured image would then show as expected on the Page where it was set.

**Comment by igielskv** [comment]
Maybe I'm doing something wrong, I have tried to point the Posts Page to various different pages with Featured Image set, but it does not show the image when Posts Page is displayed.

I have my WP setup simply like on the picture here:

<img width="454" alt="screenshot 2018-11-10 at 17 11 30" src="https://user-images.githubusercontent.com/7470561/48303689-74b2a380-e50d-11e8-9d17-c61c3100a328.png">

Then I tried to edit the Posts Page and set the Featured Image, which shows on the picture here:

<img width="1152" alt="screenshot 2018-11-10 at 17 10 57" src="https://user-images.githubusercontent.com/7470561/48303704-ca874b80-e50d-11e8-8599-5bb96cf192d0.png">

When I use the Twenty Nineteen theme bundled with the WordPress 5.0-beta3-43883, it shows the image at least in the editor, as you can see on the picture above. When I try to use the version from 
https://github.com/WordPress/twentynineteen repository it even doesn't show the image in the editor as you see here:

<img width="298" alt="screenshot 2018-11-10 at 17 07 45" src="https://user-images.githubusercontent.com/7470561/48303729-3ff31c00-e50e-11e8-87db-91c7ec45fe86.png">

**Comment by joyously** [comment]
Did you switch themes and get the same result?

**Comment by igielskv** [comment]
If you mean those two themes, the one from WordPress 5.0-beta3-43883 bundle and one from 
https://github.com/WordPress/twentynineteen repository, then Yes, I have tried to switch between them couple times, to find out the difference.

**Comment by joyously** [comment]
No, I mean any other theme besides Twenty Nineteen.

**Comment by igielskv** [comment]
I just did few tests... It seems like it's probably not particularly Twenty Nineteens theme related issue. I tried to switch back to Twenty Seventeen theme and it shows exactly the same behavior (of course there is an option for Header Media in page customization, but if we disregard this, the Featured Image in all Posts Page editor doesn't actually show on the all Posts Page in Twenty Seventeen theme as well).

I don't know, may be it's standard WordPress behavior... I'm little new to this and I didn't try before. I'm just testing this feature with WordPress 5.0-beta3-43883 running Twenty Seventeen / or Nineteen theme.

Would be nice if someone can check on official WP release 4.9.8 if Featured Image on all Posts Page works or not. And if not, then it's probably good idea to either remove that option to set Featured Image when editing especially this all Posts Page or better make it work (like it works when editing all other pages). Otherwise this settings is confusing.

**Comment by WPprodigy** [comment]
So there are actually two things reported here.

### 1) The featured image doesn't show in the classic editor.

I was able to replicate this even on a standard non-posts-page using the latest from master. This is a bug for sure.

### 2) The featured image on the posts-page doesn't show on the front-end.

This is indeed standard behavior, however - it is often a point of confusion. I wonder if twentynineteen could set a new precent here? I don't really see a downside to supporting featured images on the blog page, as you are only given an option and not taking anything away.

The implementation should be fairly straightforward. On the posts page, you'd need to check for a featured image on a specific page ID ( `get_option( 'page_for_posts' )` ) rather than the current page/post ID.

Just a thought.

**Comment by kjellr** [comment]
As noted over on Trac ([45325](https://core.trac.wordpress.org/ticket/45325)), it might be nice to allow users to add a featured image to the top of the posts page. But since it's not necessarily important for 5.0, this can be pushed to a future release. I'm going to close this specific issue ticket — we can continue tracking this in the Trac thread for a future release. 👍
