### ISSUE TITLE
Reduce excess space at bottom of page

### ISSUE THREAD

**Issue by dartiss** [WordPress/twentynineteen#584]
There appears to be an excess amount of space at the bottom of each page - from the looks of it, the space is generally divided between being above and below the footer widget. If you don't use the footer widget, it's just a large section of space.

Here's how it looks on my site (artiss.blog)...

<img width="1022" alt="screenshot 2018-11-13 at 20 40 17" src="https://user-images.githubusercontent.com/14928971/48441864-7b971b80-e784-11e8-8ed4-199eae77d928.png">

**Comment by mrxkon** [comment]
I don't know if anything changed in the meantime on this ( last 7 days ). But this is a screenshot from my setup ( default as well ) and I don't have that big of a space, except if the OP screenshot tricks my eyes a bit.

Personally I think that the spacing between menu/first heading + content/copyright line , is really spot on and gives a good flow.

![screenshot from 2018-11-20 23-30-29](https://user-images.githubusercontent.com/22611066/48804166-8c173b00-ed1c-11e8-8b1a-45c549412c13.png)

**Comment by kjellr** [comment]
I did a little digging into this, and the extra space is added when: 

- You're logged in and can see the "Edit" link
- ... and you're viewing a single page (not a post)
- ... and you do not have any widgets in the widget area

That extra spacing doesn't show up for logged-out visitors. Since this happens under such specific criteria, the difficult part of a fix is just ensuring that a fix doesn't remove space in other viewing circumstances.

**Comment by mrxkon** [comment]
Maybe we could target the entry footer when only logged in via 1 extra rule ? Not sure where else the entry-footer would show up if no Edit exists.

i.e.

```
@media only screen and ( min-width: 768px ) {
    .logged-in .entry .entry-footer {
        margin: 1rem calc(10% + 60px) 1rem;
    }
}
```

**Comment by kjellr** [comment]
Closing, since this has been migrated over to Trac here:
https://core.trac.wordpress.org/ticket/45922
