### ISSUE TITLE
Editor styles: embed links can get too large

### ISSUE THREAD

**Issue by jeherve** [WordPress/twentynineteen#594]
#### Steps to reproduce

1. Go to Posts > Add New
2. Paste a Facebook link on its own line.
3. If that link is too long, it can get out of the embed box:

<img width="827" alt="screenshot 2018-11-14 at 11 40 50" src="https://user-images.githubusercontent.com/426388/48501283-86909100-e802-11e8-90d0-16a1f0a9c79b.png">

4. Compare this with the Twenty Seventeen theme:

<img width="718" alt="screenshot 2018-11-14 at 11 40 25" src="https://user-images.githubusercontent.com/426388/48501302-91e3bc80-e802-11e8-8ccc-16f16b349e7a.png">

**Comment by kjellr** [comment]
Thanks for the report, @jeherve. Looking into this, it seems like that placeholder area is inheriting our theme's font size rules. We _could_ override that, but it seems like something that should probably be fixed on the Gutenberg end instead (since it'd effect any theme with theme styles). 

cc-ing @jasmussen for a gut check on that before I head over there and enter the bug... 

![screen shot 2018-11-14 at 12 50 13 pm](https://user-images.githubusercontent.com/1202812/48501795-1981f900-e80c-11e8-831c-90120736d6b8.png)

**Comment by kjellr** [comment]
Thanks! Reported this in https://github.com/WordPress/gutenberg/issues/11880. I'll close this issue while we wait for a fix there. 👍
