### ISSUE TITLE
blockquote paragraphs are italic

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#63]
https://github.com/WordPress/twentynineteen/blob/7b1170c700b51ccc89479a5552c97102832b2d77/style.css#L555

If the content of a blockquote has `<em>` tags for emphasis, it won't look any different. Blockquotes are for referencing another source, not for making italic paragraphs.

**Comment by audrasjb** [comment]
Nice catch :)
As far as I know, when the text to be quoted itself contains italicized words, the classical method consists in bringing out these words by returning to the ordinary character.

**Comment by kjellr** [comment]
This is a bug actually. Default block quotes are not supposed to be italic. They're intended to match the default blockquote style you'd see in Gutenberg:

![screen shot 2018-10-17 at 1 13 02 pm](https://user-images.githubusercontent.com/1202812/47104022-7a6ae100-d20e-11e8-845f-d7866b419bd7.png)

**Comment by kjellr** [comment]
Reopening this because the bug I noted here was not actually fixed:

https://github.com/WordPress/twentynineteen/issues/63#issuecomment-430713983

When we address this, we should also be sure that the citation is styled like it would be in Gutenberg. Currently, it's fairly large:

<img width="673" alt="screen shot 2018-10-24 at 9 54 44 pm" src="https://user-images.githubusercontent.com/1202812/47471372-f39ea100-d7d7-11e8-9ff2-9f6dfc60e242.png">

Whereas that same blockquote in Gutenberg looks like this:

<img width="642" alt="screen shot 2018-10-24 at 9 59 43 pm" src="https://user-images.githubusercontent.com/1202812/47471434-247ed600-d7d8-11e8-9944-db1cd9626275.png">
