### ISSUE TITLE
Heading Align Center doesn't center on page

### ISSUE THREAD

**Issue by bph** [WordPress/twentynineteen#666]
When create a H3 heading and give it an align center, it doesn't align in the middle of the screen. It does seem to center around a different axis, though. 
Here is the video http://recordit.co/Rtu47WYmUH
It might be that the two other item after the headings (Media+Text) & (Atomic Blocks Post Grid)have an align wide. 

Using yesterday's (11/24) github version of the theme.

**Comment by richtabor** [comment]
What may be making the headings look oddly centered is how the wide aligned elements are displayed, both on the frontend and within the editor.

Here's a wide aligned image, with a centered heading: 

<img width="1369" alt="screenshot 2018-11-28 12 57 40" src="https://user-images.githubusercontent.com/1813435/49171761-3e4a9600-f30d-11e8-867a-d2a2bf0b4c1d.png">

And here's the same view with the block settings open: 

<img width="1370" alt="screenshot 2018-11-28 12 59 07" src="https://user-images.githubusercontent.com/1813435/49171820-676b2680-f30d-11e8-85ba-a4a2cde1f7fb.png">

The editor sidebar pushes into the editor, which makes the wide-aligned content smaller (which then makes the heading seem misaligned.

**Comment by richtabor** [comment]
And if we look at the full alignment setting, it's much clearer how the headings are centered similarly to the text above it (as well as all blocks without specified alignments). It does look odd though, but with the current structure (having the content blocks to the left, and not centered), I'm not sure what a better solution would look like. 

<img width="1458" alt="screen shot 2018-11-28 at 1 02 06 pm" src="https://user-images.githubusercontent.com/1813435/49172023-e1031480-f30d-11e8-8bbe-c9eacf2d51a3.png">

**Comment by kjellr** [comment]
That does appear to be the issue here. Considering the layout we're using, I don't think there's a way to improve that at this point. In the future, a solution might be to use the [`:has()` pseudo-class](https://drafts.csswg.org/selectors-4/#relational) to specify a heading that is immediately followed by an alignwide/full element, and widen it to match. For example, something like:  

```
h2:has(+ .alignfull) {
    max-width: 100vw;
}
```

However, `:has()` is just experimental at this point, and has basically [no browser support](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#Browser_compatibility). 😕 

In the meantime, there isn't much we can do, so I'll close this for now. 

Thanks for the report, and for the testing!
