### ISSUE TITLE
revisit alignleft, alignright captioned images

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#688]
This one is normal legacy content (not blocks) and using WP 4.9.8 and GB 4.5.1.

One more look at alignlet and alignright shows that images **without captions line up with the text**. 

In LTR mode, alignright on an image with a caption does not line up with the text (alignleft does).
![markup image alignment-ltr](https://user-images.githubusercontent.com/7957680/49189122-bf685400-f332-11e8-8b47-a37e2596e582.jpg)

In RTL mode, alignleft on an image with a caption does not line up with the text (alignright does).
![markup image alignment-rtl](https://user-images.githubusercontent.com/7957680/49189134-c8f1bc00-f332-11e8-9f9a-768613d7a963.jpg)

**Comment by kjellr** [comment]
Here's a screenshot using a larger screen width, to help convey the discrepancy: 

**Right-aligned Classic Editor image with no caption:**  
<img width="1440" alt="screen shot 2018-11-30 at 10 58 09 am" src="https://user-images.githubusercontent.com/1202812/49299949-023f3e80-f48f-11e8-9cd7-ab0d676367ca.png">

**Left-aligned Classic Editor image with caption:**
<img width="1440" alt="screen shot 2018-11-30 at 10 58 32 am" src="https://user-images.githubusercontent.com/1202812/49299952-04090200-f48f-11e8-9829-f6a0086cb337.png">

As noted, similar behavior occurs for left-aligned images when using RTL languages. 

The theme is designed to have these extend beyond the text column, so the outlier here is the images with no caption. In that case, the images are housed within paragraph tags when inserted via the classic editor. For example: 

```
<p>
  <img src="#" class="alignright">
  This is some text that the image will float around.
</p>
```

By contrast, a captioned image is rendered with no paragraph wrapper:  

```
<figure class="wp-caption alignright">
  <img src="#">
  <figcaption class="wp-caption-text">Caption!</figcaption>
</figure>
<p>This is some text that the image will float around.</p>
```

The `<p>` in the first example inherits our max-width styles, and prevents the image from extending beyond the content column. In order to have the image extend beyond the paragraph's width, we'd need to pull it out via negative margins or relative positioning of some sort. The markup would be very different from the markup we're currently using for all other cases though, and I'm not sure it's totally worth it.

**Comment by joyously** [comment]
OK, I think you mis-labeled your screenshot.
And yours is probably from a very wide window. Mine was from a window that was about 1020px and the captioned images don't stick out very far from the text, with still lots of white space.
Having them stick out might be the design, but it looks odd. It looks like they are the problem, not the ones that are in line with the text being the problem.

**Comment by kjellr** [comment]
I've moved this issue over to Trac here: 

https://core.trac.wordpress.org/ticket/45907

I'll close this issue for now, and we can continue discussion over in that thread. Thanks!
