### ISSUE TITLE
Main nav submenu - Fixed position cutting off

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#713]
The main nav submenu is implemented as fixed position, which cuts off the items in the wild when normally there would be a scroll overflow

**Comment by kjellr** [comment]
Here's a screenshot. In this example, the menu is cut off and it's impossible to scroll down to view the menu items at the bottom.

<img width="307" alt="screen shot 2018-12-09 at 2 51 27 pm" src="https://user-images.githubusercontent.com/1202812/49702787-24893880-fbc2-11e8-82d3-0cc1988a0408.png">

**Comment by kjellr** [comment]
The usual fix for something like this would be to apply `display: block` (instead of `table`), and `overflow-x: scroll` to the submenu. However, this would need some reworking... it appears to work at first, but I'm seeing long menus visible under their children submenus:

![menu-overflow](https://user-images.githubusercontent.com/1202812/49953744-c6fc3100-fecc-11e8-9898-321f860e3069.gif)

This may need a more creative solution. 🤔

**Comment by kjellr** [comment]
We're in the process of closing down this GitHub repository now that the theme is merged into core, so I've migrated this issue over to Trac:

https://core.trac.wordpress.org/ticket/45902

I'm closing this issue a result. Please feel free to follow up in the new thread moving forward. Thanks!
