### ISSUE TITLE
Add hex field for Custom Colors

### ISSUE THREAD

**Issue by macmanx2** [WordPress/twentynineteen#718]
Don't get more wrong, the custom color slider is impressive and really cool, but sometimes we want one color that specifically matches something like our logo.

Considering that, would you please also add a hex field option for Custom Colors?

**Comment by joyously** [comment]
This has already been suggested twice, and shot down twice.

**Comment by kjellr** [comment]
Hi @macmanx2! Thanks for the ticket. Omitting a hex color picker was an intentional design choice, made to help ensure accessible color choices. You can read more about this decision in 
https://github.com/WordPress/twentynineteen/issues/613#issuecomment-439406771. I'm going to close this issue as a duplicate, but feel free to continue to share notes here or in #613 if you'd like. Thanks again!

**Comment by macmanx2** [comment]
Thanks! Not sure how my search powers failed me this time, but the explanation there makes sense.
