### ISSUE TITLE
More (...) menu button not keyboard accessible

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#723]
The more (....) menu button has been implemented as a `span` tag and is not functional to keyboard users

**Comment by anevins12** [comment]
We've got a problem here because the JS assumes that there are only people using touch events on mobile. We need to rework this entire assumption built in to the design

**Comment by anevins12** [comment]
As demonstrated in the `toggleSubmenuDisplay` method of touch-keyboard-navigation.js, the only times the method to open the submenu is called is inside the touch events line 218 to 258.

**Comment by allancole** [comment]
> We've got a problem here because the JS assumes that there are only people using touch events on mobile. We need to rework this entire assumption built in to the design. Even if you use a <button> element, the JS simply isn't there for keyboard support at all.
…
> As demonstrated in the toggleSubmenuDisplay method of touch-keyboard-navigation.js, the only times the method to open the submenu is called is inside the touch events line 218 to 258.

This isn’t entirely true but I do agreed that there’s more work to be done here. When using the tabkey, the `focus` listener is fired and adds/removes classes to make the menu accessible with keyboards. This works regardless of screen size or zoom percentage. Take a look here: 
https://github.com/WordPress/twentynineteen/blob/99f1f818f317a9b99da3d7ec73862909ace86de4/js/touch-keyboard-navigation.js#L283 

![2019-tabs-on-mobile-2](https://user-images.githubusercontent.com/709581/49765221-c9c60e80-fc9f-11e8-94c3-8956fdca188b.gif)

To clarify why it’s done this way, the `touchstart` interactions are optimized for touch interactions, so that the experience acts more like a native mobile application with larger and easier to tap click areas and an animated fullscreen design. Since keyboard and other lo-fidelity interaction types don’t require this experience, a normal dropdown menu is used instead which is more plainly accessible (once the bugs are fixed, of course 😉). 

> The more (....) menu button has been implemented as a span tag and is not functional to keyboard users
…
> To clarify, it's not just people using keyboards, it's people using any simple-input device. Even voiceover. Some people even zoom in to 400% on small desktops.

Looking at the Controls section of the theme handbook: https://make.wordpress.org/themes/handbook/review/accessibility/required/#controls, once we switch the `<span>` elements to `<button>` elements and improve the JS as you have suggested, it should also fix the voiceover concerns you have.

**Comment by anevins12** [comment]
Okay I understand it's a feature, thanks for explaining

**Comment by allancole** [comment]
You’re right about the markup though. PR #729 appears to address it :-)

**Comment by afercia** [comment]
I'd agree with @anevins12 assuming smaller screens means onl touch interaction is a broad assumption. Data show about ~40% of screen reader users use a keyboard with their mobile device, see https://webaim.org/projects/screenreadersurvey7/#mobilekeyboard

Worth also reminding not all screen reader users are 100% blind

Besides `<span>`s and `href="#"` links used as interactive elements, which is a bit unfortunate to see in a WordPress bundled theme, there are a couple additional concerns:

1
When the "more" menu is expanded:

![screenshot 2018-12-27 at 16 01 17](https://user-images.githubusercontent.com/1682452/50484666-00b35880-09f2-11e9-982c-4b5efe939794.png)

there are several hidden tab stops: these are:
- the hidden sub-menu items that are still focusable
- all the links in the page

Actually, when the menu is open it's still possible to tab away from the menu and navigate with the keyboard through all the focusable elements in the page. 

Instead, if the intent is to show a full-screen menu, then I'd say the menu should behave like a modal and tabbing should be constrained within the modal. 

I understand the intent to implement a native-friendly menu on mobile but the current implementation comes with a very high cost in terms of accessibility and I'm not fully sure why the menu implementation has deviated from the one in Twenty Seventeen, which is way more accessible and has been broadly tested "on the field".

2
I'm not sure why some of the menus `<ul>` elements have a tabindex attribute to make them focusable. Keyboard users can tab to them but they don't have a role nor a label so they're unsemantic. Are they supposed to be interactive elements? If not, the tabindex should be removed.

3
On desktop, it is possible to tab to the more menu focusable `<ul>` element even when it's "empty": see the Chrome native focus style after the last visible menu item:

<img width="967" alt="screenshot 2018-12-27 at 16 25 05" src="https://user-images.githubusercontent.com/1682452/50485139-5557d300-09f4-11e9-93d4-fcf268a4bb33.png">

Pressing again tab, focus goes to the "More" link with the `href="#"` attribute (I guess this is supposed to be shown only on mobile?). Pressing enter does nothing of course, other than scrolling the page to the top:

<img width="1052" alt="screenshot 2018-12-27 at 16 25 09" src="https://user-images.githubusercontent.com/1682452/50485174-889a6200-09f4-11e9-8a6e-d68a9b649252.png">

I guess keyboard users are a bit surprised by this "More" link appearing, as it visually resembles a "skip link" but it isn't and it doesn't do anything.

**Comment by laurelfulford** [comment]
Thank you for the details, @afercia!

I'm testing a patch for https://core.trac.wordpress.org/ticket/45713, which covers some of the above issues, but wanted to follow up on what should be fixed with that patch, and what is still outstanding:

> 1 When the "more" menu is expanded there are several hidden tab stops

I'm far from an expert, but this looks like it's still happening for me (I managed to get myself lost behind the menu on my iPhone). I've made a separate Trac ticket for this to make sure it's not lost: 

https://core.trac.wordpress.org/ticket/45796

Just let me know if anything I've included in that ticket is incorrect, and feel free to expand on it!

> 2 I'm not sure why some of the menus <ul> elements have a tabindex attribute to make them focusable. 

This looks like it will be fixed in the patch in #45713.

> 3 On desktop, it is possible to tab to the more menu focusable <ul> element even when it's "empty": 

With the patch from #45713 is applied, this also looks like it should be fixed -- I can no longer tab to an empty more link when the menu is short, or get that 'More' link text to show.

**Comment by afercia** [comment]
Thanks @laurelfulford looks like everything is covered 🙂

**Comment by kjellr** [comment]
Thanks everyone! Since we're migrating over to Trac and it sounds like all aspects of this have been covered/tracked over there, I'm going to close this issue for now. We can continue to discuss in the Trac tickets @laurelfulford mentioned if necessary. 

Thank you!
